version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: debtpayoff-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    container_name: debtpayoff-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/debtpayoff
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: debtpayoff-frontend
    ports:
      - "3000:3000"

volumes:
  mongo-data:
